#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2014 Adams Technology Consulting
#          Gavin Adams <me@gavinadams.org>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def check_nest_arguments(params):
    access_token_url, client_secret, pin_code, settings = params

    args = " -a %s" % quote_shell_string(access_token_url)

    args += " -c %s" % quote_shell_string(client_secret)

    args += " -p %s" % quote_shell_string(pin_code)


    if "description" in settings:
        args = " -d %s" % quote_shell_string(settings["description"])

    return args

def check_nest_description(params):
    description = "Nest Thermostat"

    return description

active_check_info['nest'] = {
    "command_line"        : '$USER2$/check_nest $ARG1$',
    "argument_function"   : check_nest_arguments,
    "service_description" : check_nest_description,
    "has_perfdata"        : False,
}
