#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2014 Adams Technology Consulting
#          Gavin Adams <me@gavinadams.org>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# This check calls the program that generates the inventory data for
# the <<<nest>>> portion. It passes the only wato configured parameter.
# access_token, which is used to contact nest and get the entire structure
# of managed devices

# Each section returned by the special agent is used by the other service checks
# <<<nest_thermostat>>> or <<<nest_smokealarm>>>

# Only parameter required is the access token, which will be in the format of c.xxxxx
# where xxxx is the unique string

def agent_nest_arguments(params, hostname, ipaddress):
    args = ''

    args += quote_shell_string(params[0])

    return args

special_agent_info['nest'] = agent_nest_arguments
